site_name: Apache Kafka Studies
repo_url: https://github.com/jbcodeforce/kafka-studies.github
nav:
  - Introduction: index.md
  - Apache Kafka summary: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/readme
  - Consumer practices: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/consumers
  - Producer practices: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/producers
  - Kafka streaming notes: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/kafka-stream
  - Kafka FAQ: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/FAQ
  - Kafka Connect: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/connect
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences